### ISSUE TITLE
Trace spans are added to a single trace-id for the lifetime of llamastack server

### ISSUE THREAD

**Issue by sallyom** [meta-llama/llama-stack#1725]
### System Info

Llamastack v0.1.7 with remote-vllm

### Information

- [x] The official example scripts
- [x] My own modified scripts

### 🐛 Describe the bug

When running with `v0.1.7` various scripts that create agents using various tools, a single trace-id is generated for the lifetime of the llamastack server. Spans from unrelated agents and scripts are added to this single trace-id, until the server is stopped and restarted. `This is an issue introduced in 0.1.7`, and in 0.1.6 a single run of an agent or script produces the expected individual trace-ids with spans. 

**v0.1.6**
![Image](https://github.com/user-attachments/assets/897cde55-5f32-4c1b-87e4-71afdaa46c4b)

**v0.1.7 single trace-id**
![Image](https://github.com/user-attachments/assets/3e85264c-17d2-412d-93fb-1223bbd49f06)

**v0.1.7 single trace-id 1.9 days**
![Image](https://github.com/user-attachments/assets/916b0408-5efa-425e-bd51-b72237c2c501)

### Error logs

When collecting traces, eventually they error with grpc msg too large

```
grpc: received msg larger than max
``` 

### Expected behavior

When running various agents and scripts, the expected separate traces are generated, rather than a single trace that doesn't end.

**Comment by terrytangyuan** [comment]
> This is an issue introduced in 0.1.7

cc @ehhuang Could you take a look at this one as well? Thanks!

**Comment by dineshyv** [comment]
this should already be fixed in 0.1.8 with https://github.com/meta-llama/llama-stack/pull/1730

**Comment by sallyom** [comment]
This issue is partially still present for me, in 0.1.8. I now see various trace ids, but they don't complete. I'm seeing `root span not yet received` when viewing in grafana with 0.1.8

**grafana/tempo v0.1.8 traces**

![Image](https://github.com/user-attachments/assets/3e9028d3-ca88-4588-bdfe-eea53d32a624)

And here's what it looked like with v0.1.6:
**grafana/tempo v0.1.6**

![Image](https://github.com/user-attachments/assets/b5b31726-4171-4360-a551-9186a970195c)

I've also viewed with Dynatrace,and there, I have to search for "Spans" but usually, you can see all traces when you view "Requests" - with v0.1.6, completed traces are listed as "Requests" (don't know why they list them that way), but with v0.1.8, the default "Requests" view is empty, so looks like there's no data, unless I know to search instead for the "Spans" view.
