### ISSUE TITLE
inline `MilvusVectorIOConfig.sample_run_config` is broken

### ISSUE THREAD

**Issue by nathan-weinberg** [meta-llama/llama-stack#2561]
### System Info

N/A

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### 🐛 Describe the bug

The sample config generates the following entry for Milvus:

```yaml
  - provider_id: ${env.ENABLE_MILVUS:+milvus}
    provider_type: inline::milvus
    config:
      db_path: ${env.MILVUS_DB_PATH:=~/.llama/distributions/starter/milvus.db}
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/starter}/${env.MILVUS_KVSTORE_DB_PATH:=~/.llama/distributions/starter/milvus_registry.db}
```

Rather, the config should be generated as: 

```yaml
  - provider_id: ${env.ENABLE_MILVUS:+milvus}
    provider_type: inline::milvus
    config:
      db_path: ${env.MILVUS_DB_PATH:=~/.llama/distributions/starter/milvus.db}
      kvstore:
        type: sqlite
        namespace: null
        db_path: ${env.MILVUS_KVSTORE_DB_PATH:=~/.llama/distributions/starter/milvus_registry.db}
```

### Error logs

```
2025-06-30T17:15:53.7238495Z Traceback (most recent call last):
2025-06-30T17:15:53.7245990Z   File "<frozen runpy>", line 198, in _run_module_as_main
2025-06-30T17:15:53.7246774Z   File "<frozen runpy>", line 88, in _run_code
2025-06-30T17:15:53.7247524Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/server/server.py", line 596, in <module>
2025-06-30T17:15:53.7248166Z     main()
2025-06-30T17:15:53.7248757Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/server/server.py", line 486, in main
2025-06-30T17:15:53.7249403Z     impls = asyncio.run(construct_stack(config))
2025-06-30T17:15:53.7249673Z             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7250035Z   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
2025-06-30T17:15:53.7492848Z     return runner.run(main)
2025-06-30T17:15:53.7493482Z            ^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7494275Z   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
2025-06-30T17:15:53.7495191Z     return self._loop.run_until_complete(task)
2025-06-30T17:15:53.7495602Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7496203Z   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
2025-06-30T17:15:53.7722424Z     return future.result()
2025-06-30T17:15:53.7723010Z            ^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7724975Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/stack.py", line 272, in construct_stack
2025-06-30T17:15:53.7726531Z     impls = await resolve_impls(
2025-06-30T17:15:53.7727063Z             ^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7728572Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/resolver.py", line 145, in resolve_impls
2025-06-30T17:15:53.7730551Z     return await instantiate_providers(sorted_providers, router_apis, dist_registry, run_config, policy)
2025-06-30T17:15:53.7731617Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7733804Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/resolver.py", line 271, in instantiate_providers
2025-06-30T17:15:53.7735753Z     impl = await instantiate_provider(provider, deps, inner_impls, dist_registry, run_config, policy)
2025-06-30T17:15:53.7736434Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7737514Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/distribution/resolver.py", line 358, in instantiate_provider
2025-06-30T17:15:53.7738531Z     impl = await fn(*args)
2025-06-30T17:15:53.7738843Z            ^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7740011Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/providers/inline/vector_io/milvus/__init__.py", line 18, in get_provider_impl
2025-06-30T17:15:53.7741154Z     await impl.initialize()
2025-06-30T17:15:53.7742314Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/providers/utils/telemetry/trace_protocol.py", line 103, in async_wrapper
2025-06-30T17:15:53.7743472Z     result = await method(self, *args, **kwargs)
2025-06-30T17:15:53.7743850Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7745135Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/providers/remote/vector_io/milvus/milvus.py", line 142, in initialize
2025-06-30T17:15:53.7746309Z     self.kvstore = await kvstore_impl(self.config.kvstore)
2025-06-30T17:15:53.7746767Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-06-30T17:15:53.7747858Z   File "/home/runner/work/ramalama-stack/ramalama-stack/.venv/lib/python3.12/site-packages/llama_stack/providers/utils/kvstore/kvstore.py", line 48, in kvstore_impl
2025-06-30T17:15:53.7748908Z     if config.type == KVStoreType.redis.value:
2025-06-30T17:15:53.7749571Z        ^^^^^^^^^^^
2025-06-30T17:15:53.7749940Z AttributeError: 'str' object has no attribute 'type'
```

### Expected behavior

Sample config should be valid and working

**Comment by nathan-weinberg** [comment]
cc @mattf @franciscojavierarceo

**Comment by franciscojavierarceo** [comment]
Will fix in AM

**Comment by franciscojavierarceo** [comment]
@nathan-weinberg this should be fixed

**Comment by leseb** [comment]
FYI: this bug was not fixed :( - it was re-opened here https://github.com/meta-llama/llama-stack/issues/2740
